leftnav:
- identifier: 2c96abbe-2a1a-2bcb-6cf1-26c089e826ab
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 74d1f4ad-f2b3-5795-0960-abb949f4177f
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 013a4e1d-bc9e-55ef-b62b-2e3545139c5c
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: b658b43a-9917-6fcf-c832-da1b2273ae00
  name: Assignments
  pageRef: /pages/assignments
  weight: 40
- identifier: 4c3f522b-68c9-6358-1793-8665cc31ca8e
  name: Projects
  pageRef: /pages/projects/
  weight: 50
